name: blgv-docs-fresh
region: nyc1

domains:
- domain: docs.blgvbtc.com
  type: PRIMARY
  zone: blgvbtc.com

static_sites:
- name: docs-site
  github:
    repo: BlockSavvy/blgv-docs-production
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  routes:
  - path: / 