name: blgv-docs-advanced
region: nyc1

# Custom domains
domains:
  - domain: docs.blgvbtc.com
    type: PRIMARY
    zone: blgvbtc.com

# AI Assistant API service (must come first for proper routing)
services:
  - name: ai-assistant-advanced
    source_dir: /
    github:
      repo: BlockSavvy/blgv-docs-production
      branch: main
      deploy_on_push: true
    build_command: |
      pip install --upgrade pip &&
      pip install -r ai-assistant/requirements.txt
    run_command: python ai-assistant/blgv_advanced_financial_agent.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: FLASK_SECRET_KEY
        scope: RUN_TIME
        value: ${FLASK_SECRET_KEY}
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${DATABASE_URL}
      - key: ALPHA_VANTAGE_KEY
        scope: RUN_TIME
        value: ${ALPHA_VANTAGE_KEY}
      - key: TWELVE_DATA_KEY
        scope: RUN_TIME
        value: ${TWELVE_DATA_KEY}
      - key: PORT
        scope: RUN_TIME
        value: "8080"
    routes:
      - path: /api
      - path: /ask
      - path: /widget
      - path: /metrics
      - path: /health

# Static site for Docusaurus documentation
static_sites:
  - name: docs-site
    source_dir: /
    github:
      repo: BlockSavvy/blgv-docs-production
      branch: main
      deploy_on_push: true
    build_command: |
      npm ci &&
      npm run build
    output_dir: build
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DOCUSAURUS_URL
        value: https://docs.blgvbtc.com 