name: blgv-docs-static
region: nyc1

domains:
- domain: docs.blgvbtc.com
  type: PRIMARY
  zone: blgvbtc.com

static_sites:
- name: blgv-docs
  source_dir: /
  github:
    repo: BlockSavvy/blgv-docs-production
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  routes:
  - path: / 