name: blgv-docs-advanced
region: nyc1

# Custom domains
domains:
  - domain: docs.blgvbtc.com
    type: PRIMARY
    zone: blgvbtc.com

# Static documentation site
static_sites:
  - name: blgv-docs-site
    source_dir: /
    github:
      repo: BlockSavvy/blgv-docs-production
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    routes:
      - path: / 