name: blgv-docs
region: nyc1

# Custom domains
domains:
  - domain: docs.blgvbtc.com
    type: PRIMARY
    zone: blgvbtc.com

# AI Assistant API service (must come first for proper routing)
services:
  - name: docs-ai-assistant
    source_dir: ai-assistant
    github:
      repo: BlockSavvy/blgv-docs-production
      branch: main
      deploy_on_push: true
    build_command: |
      pip install --upgrade pip &&
      pip install -r requirements.txt
    run_command: gunicorn --bind :$PORT --workers 1 --timeout 0 app:app
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET
      - key: FLASK_SECRET_KEY
        value: ${FLASK_SECRET_KEY}
        type: SECRET
      - key: BLGV_ECOSYSTEM_MODE
        value: production
      - key: BTCPAY_API_KEY
        value: ${BTCPAY_API_KEY}
        type: SECRET
      - key: BTCPAY_SERVER_URL
        value: https://btc.gdyup.xyz
    routes:
      - path: /api
      - path: /ask
      - path: /widget
      - path: /health

# Static site for Docusaurus documentation
static_sites:
  - name: docs-site
    source_dir: /
    github:
      repo: BlockSavvy/blgv-docs-production
      branch: main
      deploy_on_push: true
    build_command: |
      npm ci &&
      npm run build
    output_dir: build
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DOCUSAURUS_URL
        value: https://docs.blgvbtc.com 